### ISSUE TITLE
(ArgumentError) unknown registry: Mox

### ISSUE THREAD

**Issue by caalberts** [plataformatec/mox#1]
I came across Mox and tried to use it in my project, however I came across this error when setting the expectation. Am I missing something in the project set up? I followed the documentation closely

```
     test/controllers/app_controller_test.exs:11
     ** (ArgumentError) unknown registry: Mox
     code: |> expect(:search, 1, fn(_) -> {:ok, mock_results} end)
     stacktrace:
       (elixir) lib/registry.ex:926: Registry.info!/1
       (elixir) lib/registry.ex:808: Registry.register/3
       lib/mox.ex:155: Mox.expect/4
       test/controllers/app_controller_test.exs:18: (test)
```

**Comment by josevalim** [comment]
You need to start the `:mox` dependency before you use it. Since Mox requires Elixir v1.4, the best way to do this is to remove the `:applications` key from `def application`, since it is automatically inferred by Elixir. I will update the docs to make it clear. Thanks!

**Comment by caalberts** [comment]
👍
