### ISSUE TITLE
Errors in tests are masked by the suggested "verify!()" in the after block

### ISSUE THREAD

**Issue by whatyouhide** [plataformatec/mox#11]
Today if I have code like this:

```elixir
test "some test" do
  expect(MyModule, :my_fun, fn -> :ok end)
  raise "foo"
  assert MyModule.my_fun() == :ok
after
  verify!()
end
```

it is hard to discover errors. This is because `raise "foo"` will raise the `RuntimeError` that I want to see, but since `after` is executed anyways, `verify!()` executes anyways and it fails saying that `MyModule.my_fun/0` should've been called once but was never called.

**Comment by hubertlepicki** [comment]
@whatyouhide what do you suggest would be better behavior?

**Comment by josevalim** [comment]
@hubertlepicki now that you have removed the registry, we can actually do clean-up on `on_exit` and not require users to do it directly on the test.

In other words, we can do this:

    setup do
      on_exit &verify!/0
    end

The question is if we want users to set the on exit manually or if we should do it automatically (similar to how it is done on [bypass](https://github.com/PSPDFKit-labs/bypass/blob/9d02011400968a60b8d61486accc037d8e02048b/lib/bypass.ex#L39)).

**Comment by idlehands** [comment]
Isn't this just a function of `verify!()` being in the after block? Playing around with it, I seem to get the behavior I want if I just call verify as the last line of the test without the after.

**Comment by josevalim** [comment]
@idlehands you are right that the `after` block is completely unnecessary.

**Comment by hubertlepicki** [comment]
Yes. I can do it tonight in fact :) will send a pr

**Comment by josevalim** [comment]
@hubertlepicki i have already changed the docs, so it is a matter of deciding if we want to support on_exit verify. We can decide it on our own time since this issue is immediately solved.

**Comment by hubertlepicki** [comment]
I think we do. I have been using mox in a client project already and we're actually forgetting to add `verify!/` at the end of some tests and then we're not seeing failures (and live happily in ignorance).

I think putting it with setup/on_exit block would allow us to do it in one place in the project and be safe.

**Comment by hubertlepicki** [comment]
@josevalim if we want to support it, we could do it with optional parameter to `verify!/0` that would be turned into `verify!/1`. Then a user could place in such code in their setup block:

    setup do
       test_pid = self()
       on_exit (fn -> verify!(test_pid))
    end

We could also fold this into a little macro and use it:

    setup do
      Mox.install_verify_on_exit!()
    end

if that helps :)

**Comment by hubertlepicki** [comment]
Ugh, this is not going to work since test process is already dead when on_exit clause executes. Damn.

**Comment by josevalim** [comment]
> Mox.install_verify_on_exit!()

I love this idea. This means we can tell the server to not erase the data on DOWN and we will do it later. It also means the function is imported so users just need to write:

  setup :verify_on_exit!

I can work on those changes after I merge your improvements to the server (hopefully today).

**Comment by josevalim** [comment]
v0.2 is out with support for `setup :verify_on_exit!`.
