### ISSUE TITLE
Set :verify_on_exit! by default?

### ISSUE THREAD

**Issue by adamu** [plataformatec/mox#138]
Is there a common case where a user would *not* want to call `setup verify_on_exit!`?

If not, could this be something that is provided by default, e.g. via `use Mox`?

**Comment by adamu** [comment]
Thanks for the explanation.

The motivation for this was that I've seen a number of cases where `:verify_on_exit!` was not called in tests, which resulted in a test file with `expect` calls that looked like they were verifying the mocks, but actually were not.

I implemented this suggestion locally with a wrapper module to avoid similar footguns (and after adding this change, identified some more tests that were not verifying the expectations).

Sharing here in case people finding this issue find it useful:

```elixir
defmodule MyApp.Mox do
  defmacro __using__(_) do
    quote do
      import Mox
      setup :verify_on_exit!
    end
  end
end
```

Then replace: `import Mox` with `use MyApp.Mox` in test files.

**Comment by yukster** [comment]
Gotta say that I've fixed a looooot of tests that missed verification over the years and I think it is a pretty significant failing of this library. If a test uses the `expect` macro it seems unlikely that the dev does *not* want the expectation verified. I don't recall any mocking library in other languages needing the extra step. I also don't think I've ever seen anyone add verification other than slapping `setup :verify_on_exit!` at the top level of the test so for most users of this library, no one seems to be getting the benefit of fine-grained verification.  My two cents...

**Comment by whatyouhide** [comment]
While I don't want to get `verify_on_exit!()` by default, I agree that it might be a pretty common trip up. @josevalim what if we set a "warning" `on_exit` callback whenever you call `expect`/`stub`/etc.? Not sure how to override that since usually you'd call `verify_on_exit` first, but you get the idea.
