### ISSUE TITLE
Is there a way to verify valid return types from mocks?

### ISSUE THREAD

**Issue by aaronrenner** [plataformatec/mox#14]
I'm curious if there is a way to verify the return types from a function that's been defined with expect/3?

For example,

```elixir
defmodule Fetchable do
  @callback fetch(term) :: {:ok, term} | {:error, :not_found}
end

Mox.defmock(FetchableMock, for: Fetchable)

FetchableMock
|> expect(:fetch, fn _ -> :not_found)
```

I'm currently using behaviours + plain-old modules for mocks in test/support and diaylzer is able to catch if I return the wrong type from the mock's function. I like the ability to define an expectation and function stub explicitly in the test, but I'm worried I'm going to lose the helpful type checking provided by dialyzer.

**Comment by josevalim** [comment]
If your code is not checking for the output in any way, then it won't fail, and then you won't have the guarantees you ask for. So no, it won't replace dialyzer for those checks.

**Comment by msz** [comment]
Excuse me for being a necromancer here, but if anyone else is looking for this (like I was), I wrote an enhancement of Mox for this exact use case called [Hammox](https://github.com/msz/hammox). It will stop you for using a value not conforming to typespecs of parameters or return values. Hope it helps someone!
