### ISSUE TITLE
Support stub functions

### ISSUE THREAD

**Issue by brandonjoyce** [plataformatec/mox#2]
```
CalcMock
|> stub(:add, fn(x, y) -> x + y end)

CalcMock.add(1, 2) # 3
CalcMock.add(2, 3) # 5
```
It can be called zero to infinity times and won't be included in verification when `verify!()` is called.  This would be useful in shared setups where a few different functions may or may not be called.  It lets you write more focused expectations per test.  

I have a few other ideas, and would be willing to pitch in on some of the work.  I've been maintaining this [Double](https://github.com/sonerdy/double) package that takes a different approach for a while, but I like what I'm seeing here better already.

**Comment by hubertlepicki** [comment]
I was about to submit the same issue. 5 minutes later :)

**Comment by josevalim** [comment]
@brandonjoyce a PR is definitely welcome. Do both of you think `allow` is the best verb to use in this case?

**Comment by hubertlepicki** [comment]
@josevalim I had the same idea as @brandonjoyce, obviously influenced by my previous experience with [Rspec Method Stubs](https://relishapp.com/rspec/rspec-mocks/v/2-14/docs/method-stubs)

**Comment by brandonjoyce** [comment]
I'll probably get a start on this this evening, and we can change the verb if someone suggests something better.

**Comment by josevalim** [comment]
Perfect.

**Comment by josevalim** [comment]
Thanks @brandonjoyce! I will review the PR soon but I think we can continue with the name discussion here.

Given #5, I would rather reserve the verb `allow` to allow third party processes to use the mock. How do you feel about using `stub` instead of `allow`?

**Comment by brandonjoyce** [comment]
`stub` seems completely reasonable to me.
