### ISSUE TITLE
Just a heads up - one might need to `require` the behaviours

### ISSUE THREAD

**Issue by svarlet** [plataformatec/mox#20]
Hi,

I spent some time today trying to understand why I would get a compile time error saying that the module defining my behaviour wasn't available.

It seems that the compiler wasn't compiling the behaviour before test/support/mock.ex. I originally fixed it by adding this in `test/support/mock.ex` file:
```
Code.ensure_compiled?(MyBehaviour)
```
 
Then I realized that `require MyBehaviour` works too (even if the behaviour doesn't define any macro).

It did not happen with every mock but always with the same one. Once it works, only a `mix clean` can cause the failure to happen again. This means it could work or get fixed on one machine and break on a coworker's computer.

I do not know yet if **all** behaviours should be required beforehand. I suppose it would help to mention this whole situation in the docs.

**Comment by josevalim** [comment]
It is a bug that has been fixed in master. :) You shouldn't need to require nor anything else. :) Thanks for the report though!
