### ISSUE TITLE
Mocks for functions with optional argument

### ISSUE THREAD

**Issue by aharpole** [plataformatec/mox#39]
I am trying to use a mock for a function that has an arity of 4 according to its behaviour, but its last argument is optional. 

I set up the mocking behavior like this:

```elixir
MyApp.MockModule
|> expect(:do_something, fn arg1, arg2, arg3, arg4 -> :response end)
```

The code I'm testing calls this function with three arguments.

When I try running the tests, this fails:

```
** (UndefinedFunctionError) function MyApp.MockModule.do_something/3 is undefined or private. Did you mean one of:
     
           * do_something/4
```

Using an anonymous function with arity of 3 doesn't work on its own because the behaviour I'm mocking only specifies the function with arity of 4. 

As a workaround, I added an extra `@callback` to the behaviour with the different arity. 

As far as workarounds go, this is pretty painless, and the case could be made that it's actually better to be explicit in your behaviour that it's possible to call the function with either 3 or 4 arguments. But since Mox's documentation doesn't seem to specify anything about optional arguments I wanted to check and make sure this is intentional behavior and not a bug in Mox itself.

**Comment by josevalim** [comment]
Yes, functions in Elixir are identified by name and arity. If a function of arity 3 is part of your contract, then you need to mock it. If both are in your contract, then you need to mock each accordingly.
