### ISSUE TITLE
Apply calls to functions with matching arguments

### ISSUE THREAD

**Issue by brandonjoyce** [plataformatec/mox#4]
Should we support this?
```
CalcMock
|> expect(:add, fn(1, 1) -> 2 end)
|> expect(:add, fn(2, 2) -> 4 end)
CalcMock.add(2, 2) # 4
```
This is useful when expectations are more focused on the arguments and unique outputs than on the order the functions are called in.  I'm afraid to show how I support this in double, but here you go: https://github.com/sonerdy/double/blob/master/lib/double/func_list.ex#L98
Try not to go blind looking at that.  There must be a better way!

I suppose the workaround for this would be to just write a more advanced stub:
```
CalcMock
|> expect(:add, fn(x, y) -> 
  case {x, y} do
    {1, 1} -> 2
    {2, 2} -> 4
  end
end)
CalcMock.add(2, 2) # 4
```

**Comment by josevalim** [comment]
The "workaround" is:

```
CalcMock
|> expect(:add, fn 1, 1 -> 2; 2, 2 -> 4 end)

CalcMock.add(2, 2) # 4
```

:)

**Comment by brandonjoyce** [comment]
Nice!  Didn't know that was a thing.  👍   The only downside is that you still have to set these up in one shot, but I think I can live without this.

**Comment by joefiorini** [comment]
@brandonjoyce Thanks for opening this one, just saved me a lot of effort!
