### ISSUE TITLE
`stub_with/2` can only be used inside of a test

### ISSUE THREAD

**Issue by AaronJamesKing** [plataformatec/mox#41]
Hello!

I was reading through the documentation and found `stub_with/3`, which seems like it would be very useful for e.g. implementing both unit test and integration tests within the same `test` environment.

The documentation gives an example in which `stub_with/2` is called directly after `defmock/2`, but this doesn't seem possible. [Here's a small project to demonstrate this](https://github.com/AaronJamesKing/mox_issue). I'm using a `test/support/mocks.ex` file, but `stub_with/3` can't be used in there. That makes sense to me. But then I tried putting it in `test_helper.exs`, and even inside `example_test.exs` (outside of the test), but neither of those work either. The function *only* works when it's used inside of the `test` macro.

I guess this makes sense from a process perspective, but it seems like I shouldn't have to call `stub_with/3` during every test. Is there any way around this at all? The only reason I'm concerned about this is that, in a large project, each integration test would have to `stub_with/3` at least a few modules. I'd rather just `stub_with/3` all necessary modules at once.

As a side note: am I going about this completely wrong? This is just one of many issues I've encountered while trying to set up unit test _and_ integration tests _and_ acceptance tests altogether. Using the generally-accepted `Application.get_env/3` pattern to set up unit tests seems to make other kinds of test very difficult.

**Comment by josevalim** [comment]
You can use ExUnit.CaseTemplate with setup_all if you need to set the same
stubs over and over again.

Mox is meant to be process based and explicit, so this behavior is pretty
much intentional.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by AaronJamesKing** [comment]
Thanks for the quick response, José.

I tried placing `stub_with/2` in a `setup_all` block, both inside the test module and inside of a `use`'d CaseTemplate. In both cases, I still get this error:

`** (Mox.UnexpectedCallError) no expectation defined for Dependency.Mock.hello/0 in process #PID<0.174.0>`

(The example repository is updated with these changes)

**Comment by josevalim** [comment]
It needs to be inside `setup`, since `setup_all` runs in a separate process. Sorry for the bad advice. :)

**Comment by AaronJamesKing** [comment]
Got it, thank you!
