### ISSUE TITLE
It would be nice if Mox.allow/3 did not fail in global mode

### ISSUE THREAD

**Issue by axelson** [plataformatec/mox#46]
Currently `Mox.allow/3` raises an `ArgumentError` when it is in global mode: https://github.com/plataformatec/mox/blob/v0.4.0/lib/mox.ex#L458

For my use case it would be nice if it merely returned an `:ok/:error` tuple. Perhaps it would make sense to move the current code to `Mox.allow!/3`?

The full use case is that we have a small shim for instantiating a `Task`. The shim records the parent pid, then when it executes the task it calls both `Ecto.Adapters.SQL.Sandbox.allow/3` and `Mox.allow/3` to allow for concurrent testing.

**Comment by josevalim** [comment]
I think it makes sense for it to work because an allow on the global mode will always succeed. How does the Ecto Sandbox behave in this case?

**Comment by axelson** [comment]
It looks to me that regardless of whether the sandbox is in `:shared` mode or not calling `Sandbox.allow/3` will store the allowance in the state: https://github.com/elixir-ecto/db_connection/blob/210c0c5c82bf1d421333dab582c84818a061bf6b/lib/db_connection/ownership/manager.ex#L191

Also if you call `Ecto.Adapters.SQL.Sandbox.allow(repo, parent_pid, self())` twice the first time it will return `:ok` and the second it will return `{:already, :allowed}` (without raising an error):
https://github.com/elixir-ecto/db_connection/blob/210c0c5c82bf1d421333dab582c84818a061bf6b/lib/db_connection/ownership/manager.ex#L95

So based on that I think the spirit of this change is compatible with Ecto's sandbox feature. Although the current return value of `Mox.allow/3` may make this a little tricky. Since `Mox.allow/3` returns the `Mock` in the success case it would be a breaking change the result to an `:ok`/`:error` tuple. Although I personally wouldn't expect that many users are using the return value of `Mox.allow/3` since you could just make a repeated call with the same mock variable.

So you could change:
```
Mox.allow(MyApp.ExampleMock, parent_pid, self())
|> Mox.allow(other_parent_pid, self())
```

to:
```
Mox.allow(MyApp.ExampleMock, parent_pid, self())
Mox.allow(MyApp.ExampleMock, other_parent_pid, self())
```

Although I can't think of a reason that you'd call `Mox.allow/3` two times in a row on the same mock, but perhaps you'd call `Mox.allow/3` and then `Mox.stub/3` (in which case the refactoring is the same).

So given that I think this would be my suggestion for the implementation of `Mox.allow/3`:
```
```

**Comment by josevalim** [comment]
For now, I think we can just make sure it doesn't fail on global mode, without changing its return type.

**Comment by axelson** [comment]
Okay, that sounds good to me. I can prepare a PR.
