### ISSUE TITLE
Mock only some tests

### ISSUE THREAD

**Issue by tielur** [plataformatec/mox#47]
Is there a way to use a Mock for only some tests?

 I've seen the suggestion of calling `Mox.defmock` and `Application.put_env` in the `test_helper.exs`. 

My problem is that I want to mock my behavior for some tests but when I test the actual implementation of the behavior I don't want to mock it. 

I've tried moving the `Mox.defmock` and `Application.put_env` into a `setup` block for specific tests but it seems like calling `Mox.defmock` anywhere causes all tests to use the mock?

**Comment by josevalim** [comment]
Mox.defmock only defines the mock. Unless you are defining the mock with the name of an existing module, it should not affect your application at all. But not the Application.put_env call is global, so if you change it, you need to remember to revert its value back.

**Comment by tielur** [comment]
That makes sense, thanks José
