### ISSUE TITLE
Would it be possible to capture arguments on calls to expectations?

### ISSUE THREAD

**Issue by tpitale** [plataformatec/mox#51]
Sometimes it would be nice to know that a mocked call wasn't just called N times, but perhaps which arguments it was called with. I think I see a place where it could be hooked in. But, I'm not sure if this is something of interest to the maintainers, or what the interface to retrieve those arguments would be (maybe a return from `verify!`).

If you'd like, I can submit a PR. Or, if there is a better way to accomplish this I'm happy to add it to the documentation.

Thanks!

**Comment by josevalim** [comment]
Thanks for asking @tpitale but right now we prefer for you to match on those by passing the callback or, in a more generic fashion, pass a callback that sends a message to the test process with the arguments.

**Comment by josevalim** [comment]
Just to clarify:

```
test "invokes add and mult" do
  MyApp.CalcMock
  |> expect(:add, fn x, y -> x + y end) # you can assert here

  assert MyApp.CalcMock.add(2, 3) == 5
end
```

Or something like this:

```
test "invokes add and mult" do
  parent = self()

  MyApp.CalcMock
  |> expect(:add, fn x, y -> send parent, {:add, x, y} end)

  assert MyApp.CalcMock.add(2, 3) == 5
  assert_received {:add, 2, 3}
end
```

The above can likely be generalized. for example, you can create a function that writes the expectation for you, sends the message (or stores it elsewhere) and then use assert_verify to match on it.

**Comment by tpitale** [comment]
Thanks so much @josevalim. That was what I was thinking of doing, but this makes it much clearer.

Just quick follow up, what is `assert_verify`? Is that part of Mox?

**Comment by josevalim** [comment]
Sorry, I meant to say you could implement your own `assert_verify` (which would be a wrapper around assert_receive, but for example you could tag the messages to avoid false positives with other messages).
