### ISSUE TITLE
Use $callers to automatically add allowances

### ISSUE THREAD

**Issue by axelson** [plataformatec/mox#52]
If I'm understanding the "Improved instrumentation and ownership with `$callers`" portion of the [Elixir 1.8.0 announcement](https://elixir-lang.org/blog/2019/01/14/elixir-v1-8-0-released/) then it should be possible to use `$callers` to automatically add allowances, is that correct? If so then I can work on a PR.

**Comment by josevalim** [comment]
Yes!!! I would love a PR.
