### ISSUE TITLE
A failed assertion inside an expectation lets the test pass

### ISSUE THREAD

**Issue by svarlet** [plataformatec/mox#57]
Hi,

I wonder if it's a misunderstanding on my side or a bug. 

Given a behaviour like this:
```
defmodule EventDispatcher do
  @callback dispatch(term()) :: :ok
end
```

And this test:
```
defmodule MyTest do
  use ExUnit.Case
  import Mox

  setup verify_on_exit!

  test "this test will pass but it shouldn't" do
    expect(EventDispatcherMock, :dispatch, fn _ ->
      assert false
    end
    DispatcherExample.run()
  end
end
```

And this production code
```
defmodule DispatcherExample do
  # I would normally rely on Application.get_env to
  # get the module but for the sake of conciseness:
  @event_dispatcher EventDispatcherMock

  def run() do
    @event_dispatcher.dispatch(:foo)
  end
end
```

And of course in the test_helper file:
```
Mox.defmock(EventDispatcherMock, for: EventDispatcher)
```

I want to use this pattern to make sure that 1) an event is dispatched and 2) the event has the right properties (key and values if it's a map for example).

When I run this test, it passes. When I `IO.puts` something from within the anonymous function, I see the output *if* it happens before the assert expression. It looks like assert raises an error which is then swallowed by Mox, thereby preventing the test to report a failure. So, bug or misunderstanding?

**Comment by svarlet** [comment]
Oh well, I should have tried this example because it behaves as expected. It does performed as reported here in my real project though ... 😭

**Comment by josevalim** [comment]
What is likely happening is that you have multiple processes involved. If the code you are mocking is running in a separate process, then the assertion will happen in that separate process, causing the process to fail but necessarily the test. The test will only fail if whatever is triggering the separate process also fails once that the separate process fails.

If this is not the case and you have more information to reproduce the issue, please let us know.

**Comment by svarlet** [comment]
I explored this possibility but it's not a process related issue.

```
test "a GET /give_me_a/200 request" do
    IO.inspect self()
    expect(ClockMock, :time_now, fn -> 0 end)
    expect(ClockMock, :time_now, fn -> 10 end)
    stub(DimensionsSupplierMock, :get_dimensions, fn -> [foo: "bar"] end)
    expect(EventDispatcherMock, :dispatch, fn measurement ->
      IO.inspect self()
      assert measurement.metric_name == "ams.http.requests"
      assert measurement.latency == 10
      # assert "path:/give_me_a/200" in measurement.dimensions
      assert "http_status:2xx" in measurement.dimensions
      # assert "http_method:get" in measurement.dimensions
      assert "foo:bar" in measurement.dimensions
    end)
    canned_response(method: :get, status: 200)
  end
```

Output:
```
Excluding tags: [:test]
Including tags: [line: "42"]

#PID<0.197.0>
#PID<0.197.0>
.

Finished in 0.1 seconds
4 tests, 0 failures, 3 excluded

Randomized with seed 346960

```

**Comment by josevalim** [comment]
Oh, interesting. Can you please provide a way to reproduce this then? I know you are being unable to reproduce it, but if we can't reproduce it, we can't fix it. :S

**Comment by svarlet** [comment]
Hi, a quick non-update to share that I haven't given up on this. It's a real problem because I basically can't trust my test suite anymore. I tried to reproduce in a dummy project but I haven't been able to reproduce yet.

**Comment by svarlet** [comment]
My bad, I got tricked by my own try/rescue.
