### ISSUE TITLE
How should I add a working example into this repo?

### ISSUE THREAD

**Issue by SophisticaSean** [plataformatec/mox#58]
I made a [repo](https://github.com/SophisticaSean/elixir_mox_example) as an example of how to use Mox because all the docs and articles I could find didn't detail the setup enough to actually get it running. 

What's the best way for me to get this added to Mox? Update the hexdocs to point to this repo? Write up a summary and throw that in the hexdocs?

I'm not sure where to put it!

**Comment by josevalim** [comment]
Please send a PR that adds it to the `examples/` folder and we can link to it from the README. Also, please make sure to remove the  .formatter, .gitignore, README and config files, as they are not necessary for the example. :) Thank you!
