### ISSUE TITLE
Mocks should be present during compilation-time to verify against Behaviour

### ISSUE THREAD

**Issue by hubertlepicki** [plataformatec/mox#6]
I might be doing something wrong, but I am following the installation instructions in the following way:

1. In my `tests/test_helper.exs` file I define my mocks:

    Mox.defmock(Core.UsersManagerMock, for: Storage.Behaviours.UsersManager)

2. In my `config/test.exs` file I declare I use these mocks:

    config :core, :users_manager,  Core.UsersManagerMock

3. In my code, in modules I declare module variable and use it instead of module names directly:

    def MyModule do
       @users_manager Application.get_env(:core, :users_manager)

        def do_something() do
          @users_manager.do_something()
        end
      end

When I do the above, and either run `mix test` or `MIX_ENV=test mix compile`, I am getting the following warning:

```
MIX_ENV=test mix compile
Compiling 9 files (.ex)

warning: function Core.UsersManagerMock.do_something/0 is undefined (module Core.UsersManagerMock is not available)
  lib/my_module:5
```

This is happening because `test_helper.exs` is actually an exs file, not compiled along with the rest of the files, but executed when application / test suite starts. And the mocks defined there are not available during compilation phase.

The workaround that comes to my head is to put the mocks declaration into `test/support/` directory, add it to `elixirc_paths` in a way that it'd force compilation before compilation of rest of app if `Mix.env == test`. I can't find of other solution.

Can you advise what's the best course of action?

If the workaround above is not workaround at all, but a kosher way to do it, I am happy to update the docs.

**Comment by josevalim** [comment]
> The workaround that comes to my head is to put the mocks declaration into test/support/ directory, add it to elixirc_paths in a way that it'd force compilation before compilation of rest of app if Mix.env == test. I can't find of other solution.

Yup, that's it.

**Comment by josevalim** [comment]
To expand a bit more, if the module need to be known at compilation time, then the only option is to make the mock available at compilation time too.

**Comment by hubertlepicki** [comment]
Should I update the docs or are we good with people figuring it out on their own? ;)

**Comment by josevalim** [comment]
PRs is welcome!

**Comment by hubertlepicki** [comment]
Submitted.
