### ISSUE TITLE
Feature Request: Ability to generate a mock that doesn't implement optional callbacks

### ISSUE THREAD

**Issue by axelson** [plataformatec/mox#61]
For some of my tests it would be useful to generate a Mock that does not include optional callbacks (because the specific module that it is mocking also does not define them).

Possible workarounds:
* Stub/expect a no-op version of the optional callback (not always possible)
* Define a second version of the behaviour that doesn't specify the optional callbacks at all

Would a PR be accepted that adds this functionality?

**Comment by josevalim** [comment]
Definitely, a PR is welcome. I think though the only option is the second one. Do you have an idea of how the API would look like?

**Comment by whatyouhide** [comment]
Do you always want to not generate any of the optional callbacks? As in, would something like this work?

```elixir
Mox.defmock(MyMock, for: MyBehaviour, optional_callbacks: false)
```

**Comment by axelson** [comment]
I was thinking something similar. Along the lines of:

```
Mox.defmock(MyMock, for: MyBehaviour, optional_callbacks: [on_success: 2, on_failure: 1])
```

So we can piggy back on the same syntax as specifying the optional callbacks in the first place. And if you don't want any of the optional callbacks defined then just pass an empty list. If you want the default behavior of all the optional callbacks then you would pass an atom like `:all`.

**Comment by josevalim** [comment]
@axelson in this we would need the negated version then:

```
Mox.defmock(
  MyMock,
  for: MyBehaviour,
  skip_optional_callbacks: [on_success: 2, on_failure: 1]
)
```

**Comment by axelson** [comment]
@josevalim I don't feel too strongly either way, and have begun implementation on `:skip_optional_callbacks`. But since I generally have a preference for whitelist approaches (as opposed to blacklists) I was wondering if you could share the reasoning behind your preference for the `:skip_optional_callbacks` approach.

**Comment by josevalim** [comment]
@axelson because the default is to include everything, it would be weird IMO if to skip a single one, then I need to list all of them. Does that make any sense?

**Comment by axelson** [comment]
Ah, I see. That does make sense 👍
