### ISSUE TITLE
UnexpectedCallError is not raised when all expectations are consumed if a stub is also defined

### ISSUE THREAD

**Issue by tonyvanriet** [plataformatec/mox#69]
I can't be sure that this is not the desired behavior for Mox, but I can at least say that it surprised us.

A common pattern for us has been to define a simple `stub` in the top-level `setup` of our test file so that each individual test isn't burdened with repeating that mock setup. Then, if a test needs a more complicated `stub` or we want to test with `expect`, the individual test will declare its own `stub` or `expect` as needed, overriding the simple `stub`.

Then, I noticed that when using `expect` to expect 0 calls the test did pass even though there was a bug and the implementation code *was* calling the function once.
Similarly, if the test expects 1 call, but the function is actually called twice, the test still passes.

So, it appears that after all of the expected calls are consumed, Mox passes subsequent calls to the previously declared `stub` and no longer enforces the expectation.

I'll attach a PR in a moment with a test that reproduces this failure. If this is known to be desired behavior for Mox, I could understand that, and perhaps I'll just submit a PR with some documentation warning about this behavior.

Thanks!

**Comment by josevalim** [comment]
We could make it so any stub before the expect is erased by the expect but any stub after the expect is kept. I am not sure if this is straight-forward to implement though.

**Comment by tonyvanriet** [comment]
Hi @josevalim. 

It looks like the change to get that behavior is pretty small. https://github.com/plataformatec/mox/pull/70/commits/5489afb28692416976c1aa1b20bc2f54cd2dacfc
Unfortunately it is in direct conflict with another test that ensures the stub is used after all expects are fulfilled.

Again, I can't claim that my expectations here are right for Mox, but it does seem like this fallback to the stub undermines expect's ability to ensure a function isn't called too many times.

**Comment by josevalim** [comment]
@tonyvanriet yes, let's change the existing test and add a test if a stub is added AFTER the expectations, then the stub is preserved.

/cc @bundacia @whatyouhide @hubertlepicki

**Comment by whatyouhide** [comment]
Yeah canceling the stubs defined before an expectation but not the ones after sounds like a reasonable behaviour. I would just document the hell out of it because it's a bit subtle if you don't think about it :)

**Comment by tonyvanriet** [comment]
@josevalim @whatyouhide 
#70 now has tests for stubs before and after expect, along with some documentation.
I threw the documentation at the end of the `expect/4` doc and decided not to duplicate the explanation in the `stub/3` doc. 
Let me know if you think the documentation should be presented any differently.
