### ISSUE TITLE
Waiting on expectations

### ISSUE THREAD

**Issue by whatyouhide** [plataformatec/mox#71]
One of the most common problems that I see people having when testing asynchronous Elixir code is waiting for something asynchronous to be finished.

This can often result in cases where folks mock what is called by the asynchronous code, then run the test, but the test finishes before the call to the asynchronous code is finished, and the expectation is never actually called so `verify!` fails.

I'm wondering: can Mox help in this situation? For example, could we have a way to `wait_and_verify!` that waits for a bit until expectations are called (with a timeout, like `assert_receive` or similar)? This wouldn't work with `expect(..., 0)` but maybe that's okay.

I might be missing obvious reasons why this is either not possible or a bad idea, but thought proposing it couldn't do too much harm 😄

**Comment by josevalim** [comment]
Yes, that looks like a positive feature to me. We just need to iron out the API. I think `wait_for_expectations!` with a timeout is probably good enough.

**Comment by whatyouhide** [comment]
Nice. So to clarify, we'll have:

```elixir
wait_for_expectations!(timeout \\ 5000)
wait_for_expectations!(mock, timeout \\ 5000)
```

@josevalim do you have suggestions on implementation? I was thinking to have a `GenServer.call(..., :infinity)` on the test side, and have the Mox server use `Process.send_after/3` to notify the test after `timeout` so that the test can raise. Then, every time a function is dispatched, we check if we have no more expectations and if we don't we use `GenServer.reply` on the blocked test. However I'm not super familiar with the Mox codebase so maybe there are better approaches :)

**Comment by josevalim** [comment]
We should do a call that returns immediately and then use a receive to eventually receive the event from the server. If the event is immediately available, we can send it even before we reply to the call.

The other thing I realized though is that we can achieve this today with something like this:

```
parent = self()
expect(:foo, fn -> send(parent, :done) end0
assert_receive :done
```

Isn't that enough?

**Comment by whatyouhide** [comment]
@josevalim does that guarantee that `verify!` and `verify_on_exit!` "catch" that expectation? That is, are we sure there aren't race conditions with that approach? For example, what if I receive the message but call `verify!` before the expectation function finishes so Mox still complains that it wasn't called?

**Comment by josevalim** [comment]
You need to assert the message was received before you call verify.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by whatyouhide** [comment]
@josevalim if sending a message and waiting for it is equivalent to what I originally proposed and there are no race conditions you can think of, then we probably just need to mention that in the docs. :)

**Comment by josevalim** [comment]
Sounds good to me.
