### ISSUE TITLE
Feature request: option to add @moduledoc false

### ISSUE THREAD

**Issue by chulkilee** [plataformatec/mox#73]
The mock module may be defined in the environment where `mix docs` runs for some reasons. In that case modules generated by `defmock` will be included in the final doc.

Can we add an option to skip moduledoc? something like this:

```elixir
Mox.defmock(MyApp.CalcMock, for: MyApp.Calculator, moduledoc: false)
```

**Comment by josevalim** [comment]
Yes, please do send a PR! I would even recommend setting it to false by default UNLESS a `moduledoc` option is given!
