### ISSUE TITLE
Fallback to original implementation?

### ISSUE THREAD

**Issue by PragTob** [plataformatec/mox#76]
Hello wonderful people and thank you for mox and everything else :green_heart: 

Okay, I'm currently at a client and they like elixir (yay!) but they'd really like to use mocks so sure enough I thought I'd go ahead and use mox!

One of the places where we'd specifically need it is testing phoenix controllers (basically mocking the context). However, I'd only want that to be mocked in the unit test. For acceptance tests (for instance with wallaby or others) I'd like to use the original implementation.

Is there a tried and tested way to do this?

I can see these options right now:

1. create a new environment for which the config is set to the implementation module and not the mock
2. Set the expectations explicitly back to the original implementation (through some allow magic for the pids I believe)

My personal (probably) favorite option would be:
3. when configuring the mock via `Mox.defmock` or something similar it would be allowed to set an option like `fallback: true` to enable this behaviour for the mock. The mock itself already knows what module it's mocking (thanks to explicit contracts!) so it should be rather easy to provide and fallback to.

I'm guessing you thought about this before and that there are also good reasons on why not to do this or there might be another way to achieve the same thing.

Anyhow, I'd be happy about feedback if this feature would have a chance of making it in (I'm happy to PR it pending time) or if there's another thing that we should be doing/should be looking into :)

Thanks a ton! :green_heart: :heart: :tada: 
Tobi

PS: Here have a cute bunny:

![image](https://user-images.githubusercontent.com/606517/65040988-02dd8e80-d956-11e9-877e-debf3c37f639.png)

**Comment by josevalim** [comment]
Hi @PragTob! 👋 

> when configuring the mock via Mox.defmock or something similar it would be allowed to set an option like fallback: true to enable this behaviour for the mock. The mock itself already knows what module it's mocking

I may be missing something, but defmock expects the behaviour and not the implementation.

In any case, I believe the behaviour you want to achieve can be done with [`stub_with`](https://hexdocs.pm/mox/Mox.html#stub_with/2). It basically allows you to say to provide a default implementation for all callbacks and expectations to the things of your choice.

**Comment by PragTob** [comment]
@josevalim absolutely my fault, when playing with mox I was "nasty" and defined behaviour and implementation within the same module so I assumed the wrong thing :angel: 

Thanks for the quick help as always :green_heart: Looks like stub_with is exactly what I'm looking for. :star2:  I hadn't expected it there but absolutely makes sense (from ruby I'm used to either stubbing something or mocking something hence I didn't look at the `stub*` functions, my bad though)

If I have enough time this evening expect a PR from me highlighting this somewhere in the general module descriptions to highlight this a bit more. It's a very cool feature and I foolishly only read the moduledoc and skimmed the function docs.

**Comment by josevalim** [comment]
A PR exploring this use case would be definitely welcome, thank you!
